name: Create Model

inputs:
  model:
    type: string
    description: Name of the model to export

runs:
  using: "composite"

  steps:
    - name: Create Model - ${{ inputs.model }}
      shell: bash
      run: |
        openscad -o build/${{ inputs.model }}.stl \
          -D defaultSize=$CUBE_SIZE \
          -D defaultThickness=$CUBE_THICKNESS \
          -D defaultHeight=$CUBE_HEIGHT \
          -D defaultClearance=$CUBE_CLEARANCE \
          -D defaultPegSize=$CUBE_PEGSIZE \
          -D defaultPegLength=$CUBE_PEGLENGTH \
          -D defaultPegSpacing=$CUBE_PEGSPACING \
          -D 'model="${{ inputs.model }}"' \
          main.scad
