name: Create Model

inputs:
  model:
    type: string
    description: Name of the model to export
      size:
        type: string
        description: legs dimension in mm (x and y axis)
        default: 30
        required: true
      thickness:
        type: string
        description: thickness of the leg walls in mm
        default: 2
        required: true
      height:
        type: string
        description: height of the leg in mm (z-axis)
        default: 180
        required: true
      clearance:
        type: string
        description: additional space to account for real-world print clearance (know your printer's clearance)
        default: .2
        required: true
      pegSize:
        type: string
        description: diameter of the cylinder cut out from the center-line of the leg
        default: 10
        required: true
      pegLength:
        type: string
        description: something larger than the leg size, so the peg can be cutout from both sides of the wall along an x or y axis
        default: 40
        required: true
      pegSpacing:
        type: string
        description: linear distance between peg holes in mm
        default: 5
        required: true

runs:
  using: "composite"

  steps:
    - name: Create Model - ${{ inputs.model }}
      shell: bash
      run: |
        openscad -o build/${{ inputs.model }}.stl \
          -D defaultSize=${{ inputs.size }} \
          -D defaultThickness=${{ inputs.thickness }} \
          -D defaultHeight=${{ inputs.height }} \
          -D defaultClearance=${{ inputs.clearance }} \
          -D defaultPegSize=${{ inputs.pegSize }} \
          -D defaultPegLength=${{ inputs.pegLength }} \
          -D defaultPegSpacing=${{ inputs.pegSpacing }} \
          -D 'model="${{ inputs.model }}"' \
          main.scad
