name: Create Model

inputs:
  model:
    type: string
    description: Name of the model to export
  size:
    type: string
    description: legs dimension in mm (x and y axis)
  thickness:
    type: string
    description: thickness of the leg walls in mm
  height:
    type: string
    description: height of the leg in mm (z-axis)
  clearance:
    type: string
    description: additional space to account for real-world print clearance (know your printer's clearance)
  pegSize:
    type: string
    description: diameter of the cylinder cut out from the center-line of the leg
  pegLength:
    type: string
    description: something larger than the leg size, so the peg can be cutout from both sides of the wall along an x or y axis
  pegSpacing:
    type: string
    description: linear distance between peg holes in mm

runs:
  using: "composite"

  steps:
    - shell: bash
      run: |
        mkdir -p build

    - name: Create Model - ${{ inputs.model }}
      shell: bash
      run: |
        OPENSCADPATH=./BOSL2 \
        openscad -o build/${{ inputs.model }}.stl \
          -D defaultSize=${{ inputs.size }} \
          -D defaultThickness=${{ inputs.thickness }} \
          -D defaultHeight=${{ inputs.height }} \
          -D defaultClearance=${{ inputs.clearance }} \
          -D defaultPegSize=${{ inputs.pegSize }} \
          -D defaultPegLength=${{ inputs.pegLength }} \
          -D defaultPegSpacing=${{ inputs.pegSpacing }} \
          -D 'model="${{ inputs.model }}"' \
          main.scad
