name: Create Cube Parts

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Name of the artifact for this set of customized parameters
        required: true
      size:
        type: string
        description: legs dimension in mm (x and y axis)
        default: 30
        required: true
      thickness:
        type: string
        description: thickness of the leg walls in mm
        default: 2
        required: true
      height:
        type: string
        description: height of the leg in mm (z-axis)
        default: 180
        required: true
      clearance:
        type: string
        description: additional space to account for real-world print clearance (know your printer's clearance)
        default: .2
        required: true
      pegSize:
        type: string
        description: diameter of the cylinder cut out from the center-line of the leg
        default: 10
        required: true
      pegLength:
        type: string
        description: something larger than the leg size, so the peg can be cutout from both sides of the wall along an x or y axis
        default: 40
        required: true
      pegSpacing:
        type: string
        description: linear distance between peg holes in mm
        default: 5
        required: true

jobs:
  create-models:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install OpenScad
        run: sudo apt-get install -y openscad curl zip

      - name: Install BOSL2
        uses: actions/checkout@v3
        with:
          repository: revarbat/BOSL2
          ref: 27a2c524f0dffc30257d6ad399e400d8e06c022d
          path: ./BOSL2

      - run: |
          openscad --version
          mkdir -p build
          env | sort
          ls -al

      - run: |
          echo 'name: ${{ github.event.inputs.name }}'
          echo 'size: ${{ github.event.inputs.size }}'
          echo 'thickness: ${{ github.event.inputs.thickness }}'
          echo 'height: ${{ github.event.inputs.height }}'
          echo 'clearance: ${{ github.event.inputs.clearance }}'
          echo 'pegSize: ${{ github.event.inputs.pegSize }}'
          echo 'pegLength: ${{ github.event.inputs.pegLength }}'
          echo 'pegSpacing: ${{ github.event.inputs.pegSpacing }}'

      - uses: ./.github/actions/create-model
        with:
          model: leg
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: bracket
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: bracket-inner
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: fastener
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: tool
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: table-top
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: ./.github/actions/create-model
        with:
          model: top-plate
          size: ${{ github.event.inputs.size }}
          thickness: ${{ github.event.inputs.thickness }}
          height: ${{ github.event.inputs.height }}
          clearance: ${{ github.event.inputs.clearance }}
          pegSize: ${{ github.event.inputs.pegSize }}
          pegLength: ${{ github.event.inputs.pegLength }}
          pegSpacing: ${{ github.event.inputs.pegSpacing }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.name }}
          path: build/