name: Create Cube Parts

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Name of the artifact for this set of customized parameters
        required: true
      size:
        type: string
        description: legs dimension in mm (x and y axis)
        default: 30
        required: true
      thickness:
        type: string
        description: thickness of the leg walls in mm
        default: 2
        required: true
      height:
        type: string
        description: height of the leg in mm (z-axis)
        default: 180
        required: true
      clearance:
        type: string
        description: additional space to account for real-world print clearance (know your printer's clearance)
        default: .2
        required: true
      pegSize:
        type: string
        description: diameter of the cylinder cut out from the center-line of the leg
        default: 10
        required: true
      pegLength:
        type: string
        description: something larger than the leg size, so the peg can be cutout from both sides of the wall along an x or y axis
        default: 40
        required: true
      pegSpacing:
        type: string
        description: linear distance between peg holes in mm
        default: 5
        required: true

jobs:
  create-models:
    runs-on: ubuntu-latest
    env:
      CUBE_SIZE: ${{ inputs.size }}
      CUBE_THICKNESS: ${{ inputs.thickness }}
      CUBE_HEIGHT: ${{ inputs.height }}
      CUBE_CLEARANCE: ${{ inputs.clearance }}
      CUBE_PEGSIZE: ${{ inputs.pegSize }}
      CUBE_PEGLENGTH: ${{ inputs.pegLength }}
      CUBE_PEGSPACING: ${{ inputs.pegSpacing }}

    steps:
      - uses: actions/checkout@v3
      - name: Install OpenScad
        run: sudo apt-get install -y openscad curl zip

      - name: Install BOSL
        uses: actions/checkout@v3
        with:
          repository: revarbat/BOSL
          ref: v1.0.3

      - run: |
          mkdir -p build
          mkdir -p ~/.local/share/OpenSCAD/libraries/
          ln -s BOSL/  ~/.local/share/OpenSCAD/libraries/
          ls -al ~/
          ls -al

      - uses: ./.github/actions/create-model
        with:
          model: leg
      - uses: ./.github/actions/create-model
        with:
          model: bracket
      - uses: ./.github/actions/create-model
        with:
          model: bracket-inner
      - uses: ./.github/actions/create-model
        with:
          model: fastener
      - uses: ./.github/actions/create-model
        with:
          model: tool
      - uses: ./.github/actions/create-model
        with:
          model: table-top
      - uses: ./.github/actions/create-model
        with:
          model: top-plate

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: build/